apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: AzureArc-Deployment
  name: AzureArc-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: AzureArc-Deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: AzureArc-Deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
