apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: azurearc-gitops-deployment
  name: azurearc-gitops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurearc-gitops-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: azurearc-gitops-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
